prismagraphql/chromeless

package.json

Thanks for nice library. I couldn't found repository link in [npm](https://www.npmjs.com/package/chromeless). So I add repository URL in `package.json`. :)

Add Repository URL in `package.json`

---

README.md
docs/api.md

Despite the documentation says https://github.com/graphcool/chromeless/blob/master/docs/api.md#api-wait-fn is implemented it's actually not: https://github.com/graphcool/chromeless/blob/master/src/chrome/local-runtime.ts#L41 
This PR fixes the docs (despite that I hope to get it implemented soon :pray: ).

Fix README.md/api.md waitFn

---

serverless/README.md

Instead of JSON
```json
{
"endpointAddress": "xxxxx.amazonaws.com"
}
```
it will return just `xxxxx.amazonaws.com`

Simplify getting IoT endpoint address command

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

In the `CODE_OF_CONDUCT.md`, the Enforcement section lists my contact information. I'm OK being the point of contact but there may be an email address which is more appropriate (in relation to Graph Cool)?
Also noteworthy is that.. the `CONTRIBUTING.md` assumes we already have tests.

docs: initial code-of-conduct and contributing guidelines

---

CHANGELOG.md
README.md
docs/api.md
src/api.ts
src/chrome/local-runtime.ts
src/types.ts
src/util.ts

This implements an API at `setHtml()` to call [Page.setDocumentContent](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDocumentContent), allowing the user to pass arbitrary HTML to Chrome instead of calling a URL.
It also implements an API at `getHtml()` that allows the user to get the page's HTML.
Example usage:
```js
const { Chromeless } = require('chromeless')
async function run() {
const chromeless = new Chromeless()
const html = await chromeless
.setHtml('<h1>Hello world!</h1>')
.getHtml()
console.log(html)
await chromeless.end()
}
run().catch(console.error.bind(console))
```
Running this logs the following content:
```html
<html><head></head><body><h1>Hello world!</h1></body></html>
```
Another example of `getHtml()`, on an actual web page:
```js
chromeless …
```

setHtml() and getHtml() API

---

CHANGELOG.md
README.md
package.json
serverless/src/run.ts
src/api.ts
src/chrome/local-runtime.ts
src/chrome/local.ts
src/types.ts
src/util.ts
yarn.lock

Makes it so consumers can just have chrome launch automatically without starting it themselves (though they can still launch manually if they prefer).

chrome-launcher + spelling fixes + docs

---

CHANGELOG.md
README.md
docs/api.md
src/api.ts
src/chrome/local-runtime.ts
src/types.ts
src/util.ts

I have changed util `focus` method to https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-focus. If you prefer eval methods over this one I will change it.
However there is one small issue with combination of `focus` and `press`. Both implementations of `focus` dont work well with `press`. I dont know if that has something with my local environment.

feat: focus dom element

---

CHANGELOG.md
README.md
docs/api.md
src/api.ts
src/chrome/local-runtime.ts
src/types.ts

Be able to change the `User-Agent` of a http(s) request. It should be noted that this is only possible when it is called before the `.goto()` function.
Tested with RequestBin and perhaps the PR for https://github.com/graphcool/chromeless/issues/71 ?

provide .useragent() functionality

---

src/chrome/local.ts

pass the cdp options from the instantiation to CDP.new()

Pass cdp options to CDP.new()

---

README.md
docs/api.md
src/api.ts
src/chrome/local-runtime.ts
src/chrome/local.ts
src/types.ts
src/util.ts

use the current viewport functionality and provide it as an api.
Probably this was not implemented because Chromium provides more options than Nightmare/Phantomjs currently. So I created a DeviceMetrics interface as described at [Devtools Protocol](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#type-ScreenOrientation).
So `.setViewport({width: 1024, height: 600, scale: 1, ...})` is preferred above using comma separated values.
Fixes #75

provide .viewport() functionality

---

CHANGELOG.md
README.md
docs/api.md
src/api.ts
src/chrome/local-runtime.ts
src/types.ts
src/util.ts

feat: clear API

---

CHANGELOG.md
src/api.ts

If I import `chromeless` into my TypeScript project with activated `strictNullChecks` compiler option,
I get the following error: `Class 'Chromeless<T>' incorrectly implements interface 'Promise<T>'.`
This pull request fixes the error.

TypeScript error with activated strictNullChecks compiler option

---

README.md
docs/api.md
src/api.ts
src/chrome/local-runtime.ts
src/types.ts
src/util.ts

`cookiesClear` did not check if it could be executed, so added that check, but also rewrote the API names to make it more clear what both endpoints do(n't).

rewrite cookie endpoints: deleteCookies & clearCookies and fix clearCookies

---

serverless/serverless.yml

Fixes packaging excludes in the Proxy so that `chrome-launcher` dependencies are included in the deployment package. The excludeDevelopmentDependencies feature in Serverless seems to now correctly package dependencies.
Reported in https://github.com/graphcool/chromeless/issues/99#issuecomment-320076119

fix (proxy): correctly package dependencies in latest serverless@1.19.0

---

src/chrome/local-runtime.ts
src/util.test.ts

Since Windows does not use the temporary directory on `/tmp`, so the usage of `os.tmpdir()` is needed.

Fix: Generating screenshots/pdf using os.tmpdir() for Windows

---

README.md
docs/api.md
src/api.ts
src/chrome/local-runtime.ts
src/types.ts

To prevent data is cached from a previous browser session provide the functionality to clear the cache whenever needed.

provide .clearCache() functionality

---

README.md
docs/api.md
src/api.ts
src/chrome/local-runtime.ts
src/types.ts
src/util.ts

Add scrollToElement command and scrollBeforeClick option

---

CHANGELOG.md
README.md
docs/api.md
examples/mouse-event-example.js
src/api.ts
src/chrome/local-runtime.ts
src/types.ts
src/util.ts

https://github.com/graphcool/chromeless/pull/148
https://github.com/graphcool/chromeless/issues/100

feat: selectFile and selectFiles API

---

docs/api.md

You have the offset parameters the wrong way around in the docs.

Update api.md - fix scrollTo API docs

---

examples/mocha-chai-test-example.js

On line 38, `await chromeless.evaluate` was `awaitchromeless.evaluate` before

Fixes a typo

---

serverless/serverless.yml
src/chrome/local-runtime.ts

The number of s3 buckets is limited per account in s3.  As such, a common pattern is to use a single bucket and prefix the keys for s3 objects per app, etc.  This PR enables key prefixing.

allow key prefix for all s3 images, configured via environment

---

src/chrome/local.ts

By making sure we're passing the right target to newly launched chrome
instance and later into the CDP.Close(...) call
Closes #187

Fix unhandled rejection

---

README.md
serverless/README.md

Just noticed this when copy/pasting the remote config chunk into a project.

Fix a small syntax error in readme

---

README.md
docs/api.md
src/api.ts
src/chrome/local-runtime.ts
src/types.ts

Added functionality to expose Storage.clearDataForOrigin
as specified in https://chromedevtools.github.io/devtools-protocol/tot/Storage/ . This will allow the user to clear localstorage/websql etc.
For example:
await chromeless.clearStorage('http://localhost', 'local_storage, websql')
await chromeless.clearStorage('*', 'all')

Added clearStorage functionality 

---

src/chrome/local.ts
src/types.ts
src/util.ts

This commit allows accessing the chrome remote debugger running e.g. inside docker or in an otherwise custom port.
Fixes #265 #267

Supply missing host & port for CDP member methods

---

src/util.ts

Right now, the `url` property on a cookie is always overridden when `Network.setCookie` is called, even if the `Cookie` object passed has the `url` property set. This PR fixes this by using the `url` property on the passed `Cookie` if it exists, and then otherwise falling back to the `getUrlFromCookie` function.

Fix setting the URL on a cookie

---

CHANGELOG.md
src/api.ts
src/chrome/local-runtime.ts
src/types.ts
src/util.ts

This endpoint created solves an issue with 128Kb limit for AWS IoT not being able to return back an html string larger than that size via the `.html()` endpoint as discussed here: https://github.com/graphcool/chromeless/issues/114

Html Saved on S3 With URL Returned Endpoint

---

src/util.ts

The PR for adding file permissions configuration (https://github.com/graphcool/chromeless/pull/330) had a bug where the environment variable names weren't the same.
This aligns them to be `CHROMELESS_S3_OBJECT_ACL`.

Align env variables for ACL (file permissions)

---

src/api.ts

Allows type inference for generic type `U` of `evaluate`.
There may be a reason I'm missing that it doesn't already work this way that I'm missing, but it seems useful to me.
Before:
After:

use type inference for evaluate

---

src/util.ts

bugfix for html() method running as proxy

fix error caused by missing content type in html() method (fix #276, #396)
